### ISSUE TITLE
DockerHub Repository

### ISSUE THREAD

**Issue by stonedemoman** [Ranbato/nextpvr-ccextractor#1]
Howdy, not really an "issue" I just didn't know the best way to contact you. I was wondering if you plan to continue updating your dockerhub repository for nextpvr? I'm not great with docker yet and that repository makes it very simple to update my containers. Either way, thank you very much for your work! I would be lost attempting to get this working myself.

**Comment by Ranbato** [comment]
I actually built a new image a few days ago and forgot to push it.  Thanks for the reminder.
It is available now.

**Comment by stonedemoman** [comment]
Ah okay, much appreciated! I ran into an issue when trying to update to that new version on docker hub. It's looking for version 6.0.0 of Microsoft.NETCore.App but only finds 3.1.23 and will not initialize. Not sure what to do. Do I need to update that framework manually?

[NextPVR6.csv](https://github.com/Ranbato/nextpvr-ccextractor/files/9542059/NextPVR6.csv)

**Comment by Ranbato** [comment]
Crapaflapnasty!
I remember reading that in the release notes but because my test worked (against the wrong build!) I totally blew it off.

I'll fix it, retest, and push a new build.

**Comment by Ranbato** [comment]
OK, the new one is tested and available.
